# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SEEPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SEEPlayer

  target 'SEEPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SEEPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'MLeaksFinder'

end
